import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#3f4f68",
        "primary-fixed-dim": "#618eff",
        "secondary-dim": "#40506a",
        "on-error": "#ffefee",
        "surface-container-high": "#e0e3e5",
        "on-primary-fixed": "#000000",
        "on-primary-container": "#001f57",
        "surface-container-lowest": "#ffffff",
        "secondary": "#4c5c76",
        "on-tertiary-fixed-variant": "#005767",
        "surface": "#f5f6f8",
        "on-error-container": "#570008",
        "primary-fixed": "#789dff",
        "surface-tint": "#0253cd",
        "error-dim": "#9f0519",
        "tertiary-fixed-dim": "#56d0ed",
        "on-secondary": "#eef2ff",
        "primary-container": "#789dff",
        "tertiary-dim": "#005868",
        "on-secondary-fixed": "#2c3c55",
        "surface-container-low": "#eff1f3",
        "on-primary-fixed-variant": "#00276b",
        "on-surface": "#2c2f31",
        "secondary-fixed-dim": "#bfd0ee",
        "tertiary-fixed": "#66defc",
        "surface-variant": "#dadde0",
        "on-primary": "#f1f2ff",
        "on-surface-variant": "#595c5e",
        "background": "#f5f6f8",
        "surface-container-highest": "#dadde0",
        "tertiary": "#006577",
        "on-tertiary-container": "#004d5b",
        "outline": "#757779",
        "surface-bright": "#f5f6f8",
        "primary-dim": "#0048b5",
        "on-background": "#2c2f31",
        "primary": "#0253cd",
        "outline-variant": "#abadaf",
        "tertiary-container": "#66defc",
        "on-secondary-fixed-variant": "#495972",
        "surface-container": "#e6e8eb",
        "inverse-on-surface": "#9b9d9f",
        "error": "#b31b25",
        "secondary-container": "#cddefd",
        "surface-dim": "#d1d5d8",
        "error-container": "#fb5151",
        "inverse-primary": "#5c8bff",
        "inverse-surface": "#0c0f10",
        "on-tertiary-fixed": "#003843",
        "secondary-fixed": "#cddefd",
        "on-tertiary": "#def7ff",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      boxShadow: {
        "clinical": "0px 12px 32px rgba(44, 47, 49, 0.06)",
      },
    },
  },
  plugins: [],
};

export default config;
